### ISSUE TITLE
Wrong Info about our Airdrop

### ISSUE THREAD

**Issue by Adult-Genetic-Editing** [BinaryFocus/eosdocs.io#85]
My name is Greg Simpson - Founder of EDNA.
You have our name wrong, and our website wrong.
https://edna.life is the our site. 
Please correct this. My thanks!

**Comment by warrick-eosny** [comment]
Sorry about that, we'll update this shortly. In future please feel free to make a pull request for any changes you'd like.

**Comment by eny-rs** [comment]
Hi Greg, it's been updated! Thanks for letting us know! @Adult-Genetic-Editing
